### ISSUE TITLE
RequestError in adding a new object to collection

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#268]
[RequestError at _ui_entity_ddr-testing-40300_new-idservice_.zip](https://github.com/densho/ddr-local/files/3893233/RequestError.at._ui_entity_ddr-testing-40300_new-idservice_.zip)

master 4.0.0 

clicked `add object` in ddr-testing-40300 a known good testing collection

Entiat workstation

**Comment by gjost** [comment]
When you save objects the editor tries to index them with the local Elasticsearch.  I think the error is because the new Elasticsearch7 code is trying to interact with an old Elasticsearch2.* server.

The solution is to edit `/etc/ddr/ddrlocal-local.cfg` and change `[local] docstore_host` to point to an Elasticsearch7 server.

**Comment by gjost** [comment]
See https://github.com/densho/ddr-local/issues/269

This happens when using the current DDR with an old Elasticsearch server e.g. 2.4. I can't fix having the wrong server but ddr-local commit 9d16e3d for package ddrlocal-rc_4.0.0-rc3~deb9 should catch the RequestErrors so the program doesn't crash. Records in the local Elasticsearch will not be updated of course.

**Comment by pkikawa** [comment]
error in adding objects to collection
Error: {'error': RequestError(400, u'invalid_type_name_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Document mapping type name can't start with '_'", u'type': u'invalid_type_name_exception'}], u'type': u'invalid_type_name_exception', u'reason': u"Document mapping type name can't start with '_'"}})}

**Comment by sarabeckman** [comment]
Error in adding objects to collection
RequestError(400, u'invalid_type_name_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Document mapping type name can't start with '_'", u'type': u'invalid_type_name_exception'}], u'type': u'invalid_type_name_exception', u'reason': u"Document mapping type name can't start with '_'"}}) is not JSON serializable

I'm getting a full page Error not just in the git status messages. After getting the full page error I can't load any other page in Editor UI. I get the page RequestError400 when trying to load any page in Editor. (Main Editor UI page, collection list page)

**Comment by pkikawa** [comment]
rc3 for both me and sara

**Comment by gjost** [comment]
I set up a fresh Debian 9 VM, installed `ddrlocal-rc_4.0.0-rc3~deb9_amd64.deb` on it, pointed it at another VM that's running Elasticsearch 7, and was able to successfully create and edit entities, segments, and files. **NOTE: DDR no longer works with Elasticsearch 2.4**
